-   repo: git://github.com/pre-commit/mirrors-yapf
    rev: v0.29.0
    hooks:
    -   id: yapf
        files: ^(main|bot|twitter).py$
        args:
        - --diff

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        language: python

-   repo: git://github.com/pre-commit/mirrors-pylint
    rev: v2.4.4
    hooks:
    -   id: pylint
        files: ^(main|bot|twitter).py$
        args:
        - --errors-only
        - --disable=import-error
        language: python

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
    -   id: mypy
        files: ^(main|bot|twitter).py$
        language: python